### ISSUE TITLE
new Error('Chrome or Canary were not found')

### ISSUE THREAD

**Issue by kaven276** [rvagg/morkdown#34]
I'm on macos, have Chrome, but got "chrome not found" error message.

```
bash-3.2$ morkdown todo.md
/usr/local/lib/node_modules/morkdown/bin/morkdown.js:62
    throw(new Error('Chrome or Canary were not found'))
          ^
Error: Chrome or Canary were not found
    at Object.<anonymous> (/usr/local/lib/node_modules/morkdown/bin/morkdown.js:62:11)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3


bash-3.2$ uname -a
Darwin cuc-cpkfsmatoMacBook-Pro.local 10.8.0 Darwin Kernel Version 10.8.0: Tue Jun  7 16:33:36 PDT 2011; root:xnu-1504.15.3~1/RELEASE_I386 i386
```

**Comment by rvagg** [comment]
Can you tell me where your Chrome is installed? For OSX we have:

```
        '/Applications/Google Chrome.app/Contents/MacOS/Google Chrome'
      , '/Applications/Google Chrome Canary.app/Contents/MacOS/Google Chrome Canary'
      , '/opt/homebrew-cask/Caskroom/google-chrome/stable-channel/Google Chrome.app/Contents/MacOS/Google Chrome'
      , '/opt/homebrew-cask/Caskroom/google-chrome/latest/Google Chrome.app/Contents/MacOS/Google Chrome'
```

But it must not be one of those.
